# Generated by Django 5.2.13 on 2026-04-14 13:59

from django.db import migrations, models


def populate_status(apps, schema_editor):
    from django_cron.models import CronStatus
    CronJobLog = apps.get_model('django_cron', 'CronJobLog')
    CronJobLog.objects.filter(is_success=False).update(status=CronStatus.FAILED)
    CronJobLog.objects.filter(is_success=True).update(status=CronStatus.SUCCESS)


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0003_cronjoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjoblog',
            name='status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Running'), (2, 'Success'), (3, 'Failed')], db_index=True, default=0),
        ),
        migrations.RunPython(populate_status, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cronjoblog',
            name='is_success',
        ),
        migrations.AddIndex(
            model_name='cronjoblog',
            index=models.Index(fields=['code', 'status', 'ran_at_time'], name='django_cron_code_8924e0_idx'),
        ),
    ]
