# Generated by Django 5.2.18 on 2026-10-08 07:55

from django.db import migrations, models

INDEXES = [
    models.Index(fields=['code', 'start_time'], name='django_cron_code_966ed3_idx'),
    models.Index(fields=['code', 'start_time', 'ran_at_time'], name='django_cron_code_21f381_idx'),
]


def name_indexes(apps, schema_editor):
    # index_together indexes survive 0004 on PostgreSQL/MySQL but not SQLite's table rebuild.
    model = apps.get_model('django_cron', 'CronJobLog')
    for index in INDEXES:
        names = schema_editor._constraint_names(model, index.fields, index=True)
        if names:
            schema_editor.rename_index(model, models.Index(fields=index.fields, name=names[0]), index)
        else:
            schema_editor.add_index(model, index)


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0004_rename_cronjoblog_'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(name_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='cronjoblog',
                    new_name='django_cron_code_966ed3_idx',
                    old_fields=('code', 'start_time'),
                ),
                migrations.RenameIndex(
                    model_name='cronjoblog',
                    new_name='django_cron_code_21f381_idx',
                    old_fields=('code', 'start_time', 'ran_at_time'),
                ),
            ],
        ),
    ]
